#!/usr/bin/env python3
col_list= ["blue", "Columbus"] 
col_list.append("1492")
user_input = input("What is thy name?")
# print("In " + col_list[2] +" "+ col_list[1] +" "+"sailed the ocean " +" "+ col_list[0] +" "+ user_input + " fell off the boat")
print(f"In {col_list[2]}, {col_list[1]} sailed the ocean {col_list[0]}. {user_input} off the boat.")
